# Generated by Django 4.2.19 on 2025-03-20 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="category",
        ),
        migrations.AddField(
            model_name="movie",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="movies", to="movies.category"
            ),
        ),
    ]
