# Generated by Django 4.2.19 on 2025-02-28 20:41

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_movie"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "cover_image",
                    cloudinary.models.CloudinaryField(
                        blank=True,
                        default="default-category-cover.jpg",
                        max_length=255,
                        null=True,
                        verbose_name="image",
                    ),
                ),
            ],
        ),
    ]
