# Generated by Django 4.2.19 on 2025-03-09 20:44

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="cover_image",
        ),
        migrations.AddField(
            model_name="category",
            name="cover_url",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="category_covers"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
