# Generated by Django 4.2.19 on 2025-03-17 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_remove_category_cover_image_category_cover_url_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="name",
            new_name="category_name",
        ),
    ]
