name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: ${{ secrets.DB_USER || 'postgres' }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD || 'postgres' }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for PostgreSQL
        run: |
          while ! nc -z localhost 5432; do
            echo "Waiting for PostgreSQL..."
            sleep 1
          done

      - name: Apply database migrations
        env:
          DJANGO_SETTINGS_MODULE: imdb_clone.test_settings
          DB_NAME: ${{ secrets.DB_NAME || 'test_db' }}
          DB_USER: ${{ secrets.DB_USER || 'postgres' }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD || 'postgres' }}
          DB_HOST: localhost
          DB_PORT: 5432
        run: |
          python manage.py migrate
          
      - name: Run Tests
        env:
          DJANGO_SETTINGS_MODULE: imdb_clone.test_settings
          DB_NAME: ${{ secrets.DB_NAME || 'test_db' }}
          DB_USER: ${{ secrets.DB_USER || 'postgres' }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD || 'postgres' }}
          DB_HOST: localhost
          DB_PORT: 5432
          CELERY_BROKER_URL: ${{ secrets.CELERY_BROKER_URL || 'redis://localhost:6379/0' }}
        run: |
          yes "yes" | python manage.py test
